<a href="https://colab.research.google.com/github/samratpushpendra/Indian_flag/blob/main/Pandas_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Intro to Pandas**

### *Week 1*

In [216]:
import pandas as pd
pd.__version__

'2.2.2'

In [217]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes(as_frame=True)
print(type(diabetes['data']))

<class 'pandas.core.frame.DataFrame'>

In [218]:
df = diabetes.data
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

### Creating pandas dataframe from series

In [219]:
cities = pd.Series(['Delhi', 'Mumbai', 'Kolkata', 'Chennai'])
population = pd.Series([1200000, 1300000, 1250000, 1100000])

In [220]:
city_info_df = pd.DataFrame({'city':cities, 'population': population})

In [221]:
type(city_info_df)

pandas.core.frame.DataFrame

In [222]:
city_info_df

      city  population
0    Delhi     1200000
1   Mumbai     1300000
2  Kolkata     1250000
3  Chennai     1100000

## Exploring data in datframe

### Quickly examine a few entries in dataframe, first 5 and last 5

In [223]:
? df.head

In [224]:
df.head(10)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504

In [225]:
df.tail(3)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

### Find out number of rows and columns

In [226]:
df.shape

(442, 10)

Let see the names of the columns

In [227]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [228]:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

In [229]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

Let's get summary statistics

In [230]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [231]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,442.0,-2.511817e-19,0.047619,-0.107226,-0.037299,0.005383,0.038076,0.110727
sex,442.0,1.230790e-17,0.047619,-0.044642,-0.044642,-0.044642,0.050680,0.050680
bmi,442.0,-2.245564e-16,0.047619,-0.090275,-0.034229,-0.007284,0.031248,0.170555
bp,442.0,-4.797570e-17,0.047619,-0.112399,-0.036656,-0.005670,0.035644,0.132044
s1,442.0,-1.381499e-17,0.047619,-0.126781,-0.034248,-0.004321,0.028358,0.153914
s2,442.0,3.918434e-17,0.047619,-0.115613,-0.030358,-0.003819,0.029844,0.198788
s3,442.0,-5.777179e-18,0.047619,-0.102307,-0.035117,-0.006584,0.029312,0.181179
s4,442.0,-9.042540e-18,0.047619,-0.076395,-0.039493,-0.002592,0.034309,0.185234
s5,442.0,9.293722e-17,0.047619,-0.126097,-0.033246,-0.001947,0.032432,0.133597
s6,442.0,1.130318e-17,0.047619,-0.137767,-0.033179,-0.001078,0.027917,0.135612

In [232]:
df['age']

0      0.038076
1     -0.001882
2      0.085299
3     -0.089063
4      0.005383
         ...
437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, Length: 442, dtype: float64

In [233]:
type(df['age'])

pandas.core.series.Series

In [234]:
df['age'][100:105]

100    0.016281
101    0.016281
102   -0.092695
103    0.059871
104   -0.027310
Name: age, dtype: float64

In [235]:
df[['age','sex','bmi']][:5]

        age       sex       bmi
0  0.038076  0.050680  0.061696
1 -0.001882 -0.044642 -0.051474
2  0.085299  0.050680  0.044451
3 -0.089063 -0.044642 -0.011595
4  0.005383 -0.044642 -0.036385

* .loc- used as label name
* .iloc-used as integer position

In [236]:
df.iloc[441]

age   -0.045472
sex   -0.044642
bmi   -0.073030
bp    -0.081413
s1     0.083740
s2     0.027809
s3     0.173816
s4    -0.039493
s5    -0.004222
s6     0.003064
Name: 441, dtype: float64

In [237]:
df.loc[441]

age   -0.045472
sex   -0.044642
bmi   -0.073030
bp    -0.081413
s1     0.083740
s2     0.027809
s3     0.173816
s4    -0.039493
s5    -0.004222
s6     0.003064
Name: 441, dtype: float64

In [238]:
df.loc[4, 'age']

np.float64(0.005383060374248237)

In [239]:
df.loc[4, ['age','sex']]

age    0.005383
sex   -0.044642
Name: 4, dtype: float64

In [240]:
df.iloc[4,0]

np.float64(0.005383060374248237)

In [241]:
df.iloc[4, 0:2]

age    0.005383
sex   -0.044642
Name: 4, dtype: float64

In [242]:
age_df = df.loc[df.age < 5.383060e-03 ]
age_df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504
...,...,...,...,...,...,...,...,...,...,...
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
436,-0.056370,-0.044642,-0.074108,-0.050427,-0.024960,-0.047034,0.092820,-0.076395,-0.061176,-0.046641
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [243]:
age_df.iloc[0]

age   -0.001882
sex   -0.044642
bmi   -0.051474
bp    -0.026328
s1    -0.008449
s2    -0.019163
s3     0.074412
s4    -0.039493
s5    -0.068332
s6    -0.092204
Name: 1, dtype: float64

In [244]:
#age_df.loc[0]

In [245]:
import numpy as np

In [246]:
list("ABCD")

['A', 'B', 'C', 'D']

In [247]:
list("abcdefghi")

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']

In [248]:
df = pd.DataFrame(np.random.rand(9,4), index=list("abcdefghi"), columns=list("ABCD"))

In [249]:
df.shape

(9, 4)

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, a to i
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       9 non-null      float64
 1   B       9 non-null      float64
 2   C       9 non-null      float64
 3   D       9 non-null      float64
dtypes: float64(4)
memory usage: 360.0+ bytes

In [251]:
df.head(8)

          A         B         C         D
a  0.454762  0.566640  0.309446  0.284972
b  0.966250  0.294963  0.788172  0.249760
c  0.448295  0.632870  0.421117  0.377634
d  0.458589  0.871135  0.553721  0.073897
e  0.899159  0.710501  0.106679  0.027376
f  0.011122  0.521022  0.437617  0.053217
g  0.662095  0.503991  0.283497  0.965112
h  0.825969  0.448681  0.108136  0.098507

In [252]:
range(10, 110)

range(10, 110)

In [253]:
another_df = pd.DataFrame(np.random.rand(100,4), index=range(10, 110), columns=list('ABCD'))
another_df.head()

           A         B         C         D
10  0.441378  0.391347  0.680876  0.047075
11  0.001083  0.651566  0.547934  0.310783
12  0.344023  0.027365  0.660004  0.868442
13  0.326596  0.610168  0.162050  0.899650
14  0.001924  0.629878  0.417489  0.821350

In [254]:
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')

In [255]:
df.iloc [0]

A    0.454762
B    0.566640
C    0.309446
D    0.284972
Name: a, dtype: float64

In [256]:
#df.loc[0]

In [257]:
df.loc['a':'d', :]

          A         B         C         D
a  0.454762  0.566640  0.309446  0.284972
b  0.966250  0.294963  0.788172  0.249760
c  0.448295  0.632870  0.421117  0.377634
d  0.458589  0.871135  0.553721  0.073897

In [258]:
df.iloc[:2, 0:2]

          A         B
a  0.454762  0.566640
b  0.966250  0.294963

In [259]:
df.iloc[:8, 0:4]

          A         B         C         D
a  0.454762  0.566640  0.309446  0.284972
b  0.966250  0.294963  0.788172  0.249760
c  0.448295  0.632870  0.421117  0.377634
d  0.458589  0.871135  0.553721  0.073897
e  0.899159  0.710501  0.106679  0.027376
f  0.011122  0.521022  0.437617  0.053217
g  0.662095  0.503991  0.283497  0.965112
h  0.825969  0.448681  0.108136  0.098507

## Lambda function

In [260]:
selector = lambda df: df['A'] > 0.5

In [261]:
selector

In [262]:
df.loc[selector]

          A         B         C         D
b  0.966250  0.294963  0.788172  0.249760
e  0.899159  0.710501  0.106679  0.027376
g  0.662095  0.503991  0.283497  0.965112
h  0.825969  0.448681  0.108136  0.098507

In [263]:
selector = lambda df: (df['A'] > 0.5) & (df['B'] < 0.3)
df.loc[selector]

         A         B         C        D
b  0.96625  0.294963  0.788172  0.24976

In [264]:
condition_for_selection = (df['A'] > 0.5)| (df['B'] < 0.3)

In [265]:
df[condition_for_selection]

          A         B         C         D
b  0.966250  0.294963  0.788172  0.249760
e  0.899159  0.710501  0.106679  0.027376
g  0.662095  0.503991  0.283497  0.965112
h  0.825969  0.448681  0.108136  0.098507

## Adding a column in the dataframe

In [266]:
df['E'] = df['A']+ df['B']+ df['C']+ df['D']

In [267]:
df

          A         B         C         D         E
a  0.454762  0.566640  0.309446  0.284972  1.615820
b  0.966250  0.294963  0.788172  0.249760  2.299146
c  0.448295  0.632870  0.421117  0.377634  1.879917
d  0.458589  0.871135  0.553721  0.073897  1.957341
e  0.899159  0.710501  0.106679  0.027376  1.743715
f  0.011122  0.521022  0.437617  0.053217  1.022978
g  0.662095  0.503991  0.283497  0.965112  2.414695
h  0.825969  0.448681  0.108136  0.098507  1.481293
i  0.210145  0.984330  0.025958  0.599723  1.820157

In [268]:
df['F'] = df['E']*2

In [269]:
df

          A         B         C         D         E         F
a  0.454762  0.566640  0.309446  0.284972  1.615820  3.231640
b  0.966250  0.294963  0.788172  0.249760  2.299146  4.598291
c  0.448295  0.632870  0.421117  0.377634  1.879917  3.759834
d  0.458589  0.871135  0.553721  0.073897  1.957341  3.914681
e  0.899159  0.710501  0.106679  0.027376  1.743715  3.487430
f  0.011122  0.521022  0.437617  0.053217  1.022978  2.045955
g  0.662095  0.503991  0.283497  0.965112  2.414695  4.829390
h  0.825969  0.448681  0.108136  0.098507  1.481293  2.962586
i  0.210145  0.984330  0.025958  0.599723  1.820157  3.640313

In [270]:
criteria = df['A'] < 0.2

In [271]:
criteria

a    False
b    False
c    False
d    False
e    False
f     True
g    False
h    False
i    False
Name: A, dtype: bool

In [272]:
df.loc[criteria, 'A'] = 0

In [273]:
df

          A         B         C         D         E         F
a  0.454762  0.566640  0.309446  0.284972  1.615820  3.231640
b  0.966250  0.294963  0.788172  0.249760  2.299146  4.598291
c  0.448295  0.632870  0.421117  0.377634  1.879917  3.759834
d  0.458589  0.871135  0.553721  0.073897  1.957341  3.914681
e  0.899159  0.710501  0.106679  0.027376  1.743715  3.487430
f  0.000000  0.521022  0.437617  0.053217  1.022978  2.045955
g  0.662095  0.503991  0.283497  0.965112  2.414695  4.829390
h  0.825969  0.448681  0.108136  0.098507  1.481293  2.962586
i  0.210145  0.984330  0.025958  0.599723  1.820157  3.640313

In [274]:
df.shape

(9, 6)

In [275]:
cities = ['Mumbai', 'Delhi', 'Lucknow', 'Bhopal', 'Indore', 'Pune', 'Bengluru', 'Noida', 'Hydrabad']

In [276]:
df['city'] = cities

In [277]:
df

          A         B         C         D         E         F      city
a  0.454762  0.566640  0.309446  0.284972  1.615820  3.231640    Mumbai
b  0.966250  0.294963  0.788172  0.249760  2.299146  4.598291     Delhi
c  0.448295  0.632870  0.421117  0.377634  1.879917  3.759834   Lucknow
d  0.458589  0.871135  0.553721  0.073897  1.957341  3.914681    Bhopal
e  0.899159  0.710501  0.106679  0.027376  1.743715  3.487430    Indore
f  0.000000  0.521022  0.437617  0.053217  1.022978  2.045955      Pune
g  0.662095  0.503991  0.283497  0.965112  2.414695  4.829390  Bengluru
h  0.825969  0.448681  0.108136  0.098507  1.481293  2.962586     Noida
i  0.210145  0.984330  0.025958  0.599723  1.820157  3.640313  Hydrabad

In [278]:
country = ['India']*9

In [279]:
df_copy = df.copy()
df_copy['country'] = country
df_copy

,A,B,C,D,E,F,city,country
a,0.454762,0.566640,0.309446,0.284972,1.615820,3.231640,Mumbai,India
b,0.966250,0.294963,0.788172,0.249760,2.299146,4.598291,Delhi,India
c,0.448295,0.632870,0.421117,0.377634,1.879917,3.759834,Lucknow,India
d,0.458589,0.871135,0.553721,0.073897,1.957341,3.914681,Bhopal,India
e,0.899159,0.710501,0.106679,0.027376,1.743715,3.487430,Indore,India
f,0.000000,0.521022,0.437617,0.053217,1.022978,2.045955,Pune,India
g,0.662095,0.503991,0.283497,0.965112,2.414695,4.829390,Bengluru,India
h,0.825969,0.448681,0.108136,0.098507,1.481293,2.962586,Noida,India
i,0.210145,0.984330,0.025958,0.599723,1.820157,3.640313,Hydrabad,India

In [280]:
criteria = df_copy['city'].isin(['Pune', 'Mumbai', 'Lucknow'])

In [281]:
criteria

a     True
b    False
c     True
d    False
e    False
f     True
g    False
h    False
i    False
Name: city, dtype: bool

In [282]:
df_copy.loc[df.city == 'Bengluru', ['city']] = 'Kolkata'

In [283]:
df_copy

,A,B,C,D,E,F,city,country
a,0.454762,0.566640,0.309446,0.284972,1.615820,3.231640,Mumbai,India
b,0.966250,0.294963,0.788172,0.249760,2.299146,4.598291,Delhi,India
c,0.448295,0.632870,0.421117,0.377634,1.879917,3.759834,Lucknow,India
d,0.458589,0.871135,0.553721,0.073897,1.957341,3.914681,Bhopal,India
e,0.899159,0.710501,0.106679,0.027376,1.743715,3.487430,Indore,India
f,0.000000,0.521022,0.437617,0.053217,1.022978,2.045955,Pune,India
g,0.662095,0.503991,0.283497,0.965112,2.414695,4.829390,Kolkata,India
h,0.825969,0.448681,0.108136,0.098507,1.481293,2.962586,Noida,India
i,0.210145,0.984330,0.025958,0.599723,1.820157,3.640313,Hydrabad,India

In [284]:
df_copy.drop(columns='country',inplace=True)

In [285]:
df_copy.drop('i', inplace= True)

In [286]:
df_copy

          A         B         C         D         E         F     city
a  0.454762  0.566640  0.309446  0.284972  1.615820  3.231640   Mumbai
b  0.966250  0.294963  0.788172  0.249760  2.299146  4.598291    Delhi
c  0.448295  0.632870  0.421117  0.377634  1.879917  3.759834  Lucknow
d  0.458589  0.871135  0.553721  0.073897  1.957341  3.914681   Bhopal
e  0.899159  0.710501  0.106679  0.027376  1.743715  3.487430   Indore
f  0.000000  0.521022  0.437617  0.053217  1.022978  2.045955     Pune
g  0.662095  0.503991  0.283497  0.965112  2.414695  4.829390  Kolkata
h  0.825969  0.448681  0.108136  0.098507  1.481293  2.962586    Noida

In [287]:
df_copy.loc[:, 'country'] = 'Bharat'
df_copy

          A         B         C         D         E         F     city country
a  0.454762  0.566640  0.309446  0.284972  1.615820  3.231640   Mumbai  Bharat
b  0.966250  0.294963  0.788172  0.249760  2.299146  4.598291    Delhi  Bharat
c  0.448295  0.632870  0.421117  0.377634  1.879917  3.759834  Lucknow  Bharat
d  0.458589  0.871135  0.553721  0.073897  1.957341  3.914681   Bhopal  Bharat
e  0.899159  0.710501  0.106679  0.027376  1.743715  3.487430   Indore  Bharat
f  0.000000  0.521022  0.437617  0.053217  1.022978  2.045955     Pune  Bharat
g  0.662095  0.503991  0.283497  0.965112  2.414695  4.829390  Kolkata  Bharat
h  0.825969  0.448681  0.108136  0.098507  1.481293  2.962586    Noida  Bharat

In [288]:
df_copy.drop(columns='country', inplace=True)

In [289]:
?df_copy.sample

In [290]:
df_copy.sample(5, random_state=42)

          A         B         C         D         E         F     city
b  0.966250  0.294963  0.788172  0.249760  2.299146  4.598291    Delhi
f  0.000000  0.521022  0.437617  0.053217  1.022978  2.045955     Pune
a  0.454762  0.566640  0.309446  0.284972  1.615820  3.231640   Mumbai
h  0.825969  0.448681  0.108136  0.098507  1.481293  2.962586    Noida
c  0.448295  0.632870  0.421117  0.377634  1.879917  3.759834  Lucknow

In [291]:
df_copy.sample(3, replace=True)

          A         B         C         D         E         F     city
c  0.448295  0.632870  0.421117  0.377634  1.879917  3.759834  Lucknow
b  0.966250  0.294963  0.788172  0.249760  2.299146  4.598291    Delhi
g  0.662095  0.503991  0.283497  0.965112  2.414695  4.829390  Kolkata

In [299]:
Cities = ['New Delhi','Bhopal','Dehradun','Mumbai', 'Lucknow', 'Kolkata', 'Patna']
city_df = pd.DataFrame({'city':Cities})

In [300]:
city_df

        city
0  New Delhi
1     Bhopal
2   Dehradun
3     Mumbai
4    Lucknow
5    Kolkata
6      Patna

In [301]:
condition_met = city_df.city == 'Mumbai'

In [303]:
condition_met

0    False
1    False
2    False
3     True
4    False
5    False
6    False
Name: city, dtype: bool

In [302]:
type(condition_met)

pandas.core.series.Series

## Aggregation and grouping

In [311]:
import numpy as np

In [312]:
random_state = np.random.RandomState(100)
random_series = pd.Series(random_state.rand(10))

In [313]:
random_series

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
7    0.825853
8    0.136707
9    0.575093
dtype: float64

Now that the series is created, we can try aggregation functions like mean, std etc

In [314]:
random_series.std()

0.2988992029497061

In [315]:
random_series.mean()

np.float64(0.4425757785871915)

In [316]:
random_series.sum()

np.float64(4.425757785871915)

Let's create a dataframe with 5 rows and 2 columns containg random numbers

In [317]:
df = pd.DataFrame({'A': random_state.rand(5),
                   'B': random_state.rand(5)})

In [318]:
df

          A         B
0  0.891322  0.978624
1  0.209202  0.811683
2  0.185328  0.171941
3  0.108377  0.816225
4  0.219697  0.274074

In [319]:
df.sum()

A    1.613927
B    3.052546
dtype: float64

In [320]:
df.mean()

A    0.322785
B    0.610509
dtype: float64

Try all these operations row wise

In [326]:
df['sum'] = df.sum(axis=1)

In [330]:
df['mean'] = df.mean(axis=1)

In [331]:
df

          A         B       sum      mean
0  0.891322  0.978624  2.804919  1.558288
1  0.209202  0.811683  1.531328  0.850738
2  0.185328  0.171941  0.535904  0.297724
3  0.108377  0.816225  1.386902  0.770501
4  0.219697  0.274074  0.740657  0.411476

## Groupby
Three stages


*   Split - we split dataframe into multiple smaller dataframe based on the values of keys
*   Apply - we apply desired aggregation/transformation on each dataframe
* Combine - we combine results from apply state into a datarame

In [335]:
df = pd.DataFrame({'key': ['A','B','C']*2,
                   'data': range(6)})

In [336]:
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [339]:
df.groupby("key").sum()

     data
key
A       3
B       5
C       7

## Week 2